service: email-api

provider:
  name: aws
  runtime: python3.10  
  region: us-east-1

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.send_email  
    events:
      - http:
          path: send-email
          method: post
          cors: true
