# Generated by Django 5.1.6 on 2025-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
