# Generated by Django 5.1.6 on 2025-03-05 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0010_speciality_remove_appointment_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
